// ===== DONNÉES JOUEURS FC-FULBERT =====

const playersData = [
    // GARDIENS
    {
        id: 'pierre-moreau-1',
        numero: 1,
        nom: 'Pierre Moreau',
        prenom: 'Pierre',
        nomComplet: 'Pierre Moreau',
        poste: 'Gardien de but',
        position: 'gardien',
        avatar: '🧤',
        age: 30,
        dateNaissance: '15/03/1994',
        nationalite: '🇫🇷 France',
        taille: '1m88',
        poids: '85kg',
        piedFort: 'Droit',
        matchs: 26,
        buts: 0,
        passes: 0,
        cleanSheets: 12,
        cartonsJaunes: 2,
        cartonsRouges: 0,
        bio: 'Gardien expérimenté et capitaine de l\'équipe. Pierre est un véritable rempart devant les cages du FC-Fulbert depuis 8 saisons. Ses réflexes exceptionnels et son leadership font de lui un élément indispensable.',
        parcours: ['FC Dreux (2012-2016)', 'FC-Fulbert Chartres (2016-présent)']
    },
    {
        id: 'lucas-petit-16',
        numero: 16,
        nom: 'Lucas Petit',
        prenom: 'Lucas',
        nomComplet: 'Lucas Petit',
        poste: 'Gardien de but',
        position: 'gardien',
        avatar: '🧤',
        age: 24,
        dateNaissance: '22/08/2000',
        nationalite: '🇫🇷 France',
        taille: '1m85',
        poids: '80kg',
        piedFort: 'Gauche',
        matchs: 0,
        buts: 0,
        passes: 0,
        cleanSheets: 0,
        cartonsJaunes: 0,
        cartonsRouges: 0,
        bio: 'Jeune gardien prometteur formé au club. Lucas attend patiemment son heure pour montrer son talent.',
        parcours: ['FC-Fulbert U19 (2018-2020)', 'FC-Fulbert Senior (2020-présent)']
    },
    
    // DÉFENSEURS
    {
        id: 'antoine-dubois-2',
        numero: 2,
        nom: 'Antoine Dubois',
        prenom: 'Antoine',
        nomComplet: 'Antoine Dubois',
        poste: 'Arrière droit',
        position: 'defenseur',
        avatar: '🛡️',
        age: 28,
        dateNaissance: '10/05/1996',
        nationalite: '🇫🇷 France',
        taille: '1m82',
        poids: '78kg',
        piedFort: 'Droit',
        matchs: 24,
        buts: 2,
        passes: 5,
        cleanSheets: 0,
        cartonsJaunes: 4,
        cartonsRouges: 0,
        bio: 'Latéral droit offensif, Antoine apporte beaucoup dans les montées. Sa vitesse et ses centres précis en font une arme offensive importante.',
        parcours: ['US Lucé (2014-2019)', 'FC-Fulbert Chartres (2019-présent)']
    },
    {
        id: 'kevin-laurent-3',
        numero: 3,
        nom: 'Kevin Laurent',
        prenom: 'Kevin',
        nomComplet: 'Kevin Laurent',
        poste: 'Arrière gauche',
        position: 'defenseur',
        avatar: '🛡️',
        age: 26,
        dateNaissance: '18/11/1998',
        nationalite: '🇫🇷 France',
        taille: '1m80',
        poids: '76kg',
        piedFort: 'Gauche',
        matchs: 23,
        buts: 1,
        passes: 7,
        cleanSheets: 0,
        cartonsJaunes: 3,
        cartonsRouges: 0,
        bio: 'Arrière gauche solide défensivement. Kevin compense par son expérience et sa lecture du jeu.',
        parcours: ['FC Mainvilliers (2016-2020)', 'FC-Fulbert Chartres (2020-présent)']
    },
    {
        id: 'maxime-richard-4',
        numero: 4,
        nom: 'Maxime Richard',
        prenom: 'Maxime',
        nomComplet: 'Maxime Richard',
        poste: 'Défenseur central',
        position: 'defenseur',
        avatar: '🛡️',
        age: 29,
        dateNaissance: '05/01/1996',
        nationalite: '🇫🇷 France',
        taille: '1m85',
        poids: '82kg',
        piedFort: 'Droit',
        matchs: 25,
        buts: 3,
        passes: 2,
        cleanSheets: 0,
        cartonsJaunes: 6,
        cartonsRouges: 1,
        bio: 'Roc défensif du FC-Fulbert. Maxime est le patron de la défense, redoutable dans les duels aériens.',
        parcours: ['FC Vernouillet (2014-2017)', 'FC-Fulbert Chartres (2017-présent)']
    },
    {
        id: 'nicolas-simon-5',
        numero: 5,
        nom: 'Nicolas Simon',
        prenom: 'Nicolas',
        nomComplet: 'Nicolas Simon',
        poste: 'Défenseur central',
        position: 'defenseur',
        avatar: '🛡️',
        age: 27,
        dateNaissance: '12/07/1997',
        nationalite: '🇫🇷 France',
        taille: '1m83',
        poids: '79kg',
        piedFort: 'Gauche',
        matchs: 22,
        buts: 1,
        passes: 3,
        cleanSheets: 0,
        cartonsJaunes: 5,
        cartonsRouges: 0,
        bio: 'Défenseur central technique et intelligent. Nicolas compense sa taille moyenne par un excellent placement.',
        parcours: ['AS Dreux (2015-2019)', 'FC-Fulbert Chartres (2019-présent)']
    },
    {
        id: 'thomas-rousseau-12',
        numero: 12,
        nom: 'Thomas Rousseau',
        prenom: 'Thomas',
        nomComplet: 'Thomas Rousseau',
        poste: 'Défenseur',
        position: 'defenseur',
        avatar: '🛡️',
        age: 25,
        dateNaissance: '28/09/1999',
        nationalite: '🇫🇷 France',
        taille: '1m81',
        poids: '77kg',
        piedFort: 'Droit',
        matchs: 15,
        buts: 0,
        passes: 2,
        cleanSheets: 0,
        cartonsJaunes: 2,
        cartonsRouges: 0,
        bio: 'Jeune défenseur polyvalent, Thomas peut évoluer sur tous les postes de la défense.',
        parcours: ['FC-Fulbert U19 (2017-2019)', 'FC-Fulbert Senior (2019-présent)']
    },
    {
        id: 'alexandre-durand-15',
        numero: 15,
        nom: 'Alexandre Durand',
        prenom: 'Alexandre',
        nomComplet: 'Alexandre Durand',
        poste: 'Défenseur',
        position: 'defenseur',
        avatar: '🛡️',
        age: 23,
        dateNaissance: '14/04/2001',
        nationalite: '🇫🇷 France',
        taille: '1m79',
        poids: '74kg',
        piedFort: 'Gauche',
        matchs: 10,
        buts: 0,
        passes: 1,
        cleanSheets: 0,
        cartonsJaunes: 1,
        cartonsRouges: 0,
        bio: 'Espoir de la formation FC-Fulbert, Alexandre progresse rapidement et gagne du temps de jeu.',
        parcours: ['FC-Fulbert U19 (2019-2021)', 'FC-Fulbert Senior (2021-présent)']
    },

    // MILIEUX
    {
        id: 'lucas-martin-6',
        numero: 6,
        nom: 'Lucas Martin',
        prenom: 'Lucas',
        nomComplet: 'Lucas Martin',
        poste: 'Milieu défensif',
        position: 'milieu',
        avatar: '⚙️',
        age: 27,
        dateNaissance: '20/06/1997',
        nationalite: '🇫🇷 France',
        taille: '1m76',
        poids: '72kg',
        piedFort: 'Droit',
        matchs: 25,
        buts: 3,
        passes: 6,
        cleanSheets: 0,
        cartonsJaunes: 7,
        cartonsRouges: 0,
        bio: 'Récupérateur infatigable au milieu de terrain. Lucas est le poumon de l\'équipe.',
        parcours: ['FC Châteaudun (2015-2018)', 'FC-Fulbert Chartres (2018-présent)']
    },
    {
        id: 'julien-leroy-8',
        numero: 8,
        nom: 'Julien Leroy',
        prenom: 'Julien',
        nomComplet: 'Julien Leroy',
        poste: 'Milieu relayeur',
        position: 'milieu',
        avatar: '⚙️',
        age: 26,
        dateNaissance: '03/03/1998',
        nationalite: '🇫🇷 France',
        taille: '1m78',
        poids: '73kg',
        piedFort: 'Droit',
        matchs: 24,
        buts: 5,
        passes: 8,
        cleanSheets: 0,
        cartonsJaunes: 3,
        cartonsRouges: 0,
        bio: 'Box-to-box dynamique. Julien est capable d\'apporter dans les deux surfaces.',
        parcours: ['US Lucé (2016-2019)', 'FC-Fulbert Chartres (2019-présent)']
    },
    {
        id: 'david-mercier-10',
        numero: 10,
        nom: 'David Mercier',
        prenom: 'David',
        nomComplet: 'David Mercier',
        poste: 'Meneur de jeu',
        position: 'milieu',
        avatar: '⚙️',
        age: 29,
        dateNaissance: '15/08/1995',
        nationalite: '🇫🇷 France',
        taille: '1m75',
        poids: '71kg',
        piedFort: 'Gauche',
        matchs: 26,
        buts: 8,
        passes: 14,
        cleanSheets: 0,
        cartonsJaunes: 2,
        cartonsRouges: 0,
        bio: 'Maestro du FC-Fulbert. David est le créateur, le cerveau de l\'équipe. Ses passes décisives et sa vision du jeu font la différence.',
        parcours: ['FC Dreux (2013-2017)', 'FC-Fulbert Chartres (2017-présent)']
    },
    {
        id: 'florian-blanc-14',
        numero: 14,
        nom: 'Florian Blanc',
        prenom: 'Florian',
        nomComplet: 'Florian Blanc',
        poste: 'Milieu offensif',
        position: 'milieu',
        avatar: '⚙️',
        age: 24,
        dateNaissance: '09/12/2000',
        nationalite: '🇫🇷 France',
        taille: '1m77',
        poids: '70kg',
        piedFort: 'Gauche',
        matchs: 20,
        buts: 4,
        passes: 7,
        cleanSheets: 0,
        cartonsJaunes: 2,
        cartonsRouges: 0,
        bio: 'Milieu technique et créatif. Florian apporte du rythme et des solutions dans le jeu.',
        parcours: ['FC-Fulbert U19 (2018-2020)', 'FC-Fulbert Senior (2020-présent)']
    },
    {
        id: 'benjamin-fournier-17',
        numero: 17,
        nom: 'Benjamin Fournier',
        prenom: 'Benjamin',
        nomComplet: 'Benjamin Fournier',
        poste: 'Milieu',
        position: 'milieu',
        avatar: '⚙️',
        age: 25,
        dateNaissance: '25/02/1999',
        nationalite: '🇫🇷 France',
        taille: '1m74',
        poids: '69kg',
        piedFort: 'Droit',
        matchs: 18,
        buts: 2,
        passes: 5,
        cleanSheets: 0,
        cartonsJaunes: 3,
        cartonsRouges: 0,
        bio: 'Milieu polyvalent capable d\'évoluer dans plusieurs rôles au centre du terrain.',
        parcours: ['FC Mainvilliers (2017-2020)', 'FC-Fulbert Chartres (2020-présent)']
    },
    {
        id: 'mathieu-girard-18',
        numero: 18,
        nom: 'Mathieu Girard',
        prenom: 'Mathieu',
        nomComplet: 'Mathieu Girard',
        poste: 'Milieu',
        position: 'milieu',
        avatar: '⚙️',
        age: 23,
        dateNaissance: '11/06/2001',
        nationalite: '🇫🇷 France',
        taille: '1m79',
        poids: '74kg',
        piedFort: 'Droit',
        matchs: 12,
        buts: 1,
        passes: 3,
        cleanSheets: 0,
        cartonsJaunes: 1,
        cartonsRouges: 0,
        bio: 'Jeune milieu en progression constante. Mathieu gagne en maturité match après match.',
        parcours: ['FC-Fulbert U19 (2019-2021)', 'FC-Fulbert Senior (2021-présent)']
    },

    // ATTAQUANTS
    {
        id: 'julien-bernard-7',
        numero: 7,
        nom: 'Julien Bernard',
        prenom: 'Julien',
        nomComplet: 'Julien Bernard',
        poste: 'Ailier droit',
        position: 'attaquant',
        avatar: '⚡',
        age: 28,
        dateNaissance: '07/04/1996',
        nationalite: '🇫🇷 France',
        taille: '1m80',
        poids: '75kg',
        piedFort: 'Gauche',
        matchs: 25,
        buts: 12,
        passes: 9,
        cleanSheets: 0,
        cartonsJaunes: 2,
        cartonsRouges: 0,
        bio: 'Ailier explosif et technique. Julien est redoutable dans les un-contre-un et possède une frappe puissante.',
        parcours: ['AS Dreux (2014-2018)', 'FC-Fulbert Chartres (2018-présent)']
    },
    {
        id: 'alexandre-roux-9',
        numero: 9,
        nom: 'Alexandre Roux',
        prenom: 'Alexandre',
        nomComplet: 'Alexandre Roux',
        poste: 'Avant-centre',
        position: 'attaquant',
        avatar: '⚡',
        age: 26,
        dateNaissance: '19/09/1998',
        nationalite: '🇫🇷 France',
        taille: '1m82',
        poids: '77kg',
        piedFort: 'Droit',
        matchs: 26,
        buts: 18,
        passes: 4,
        cleanSheets: 0,
        cartonsJaunes: 1,
        cartonsRouges: 0,
        bio: 'Buteur prolifique du FC-Fulbert. Alexandre est un avant-centre complet : puissant, rapide et clinique devant le but. Meilleur buteur de l\'équipe cette saison.',
        parcours: ['FC Dreux (2016-2019)', 'FC-Fulbert Chartres (2019-présent)']
    },
    {
        id: 'sebastien-morel-11',
        numero: 11,
        nom: 'Sébastien Morel',
        prenom: 'Sébastien',
        nomComplet: 'Sébastien Morel',
        poste: 'Ailier gauche',
        position: 'attaquant',
        avatar: '⚡',
        age: 27,
        dateNaissance: '23/01/1998',
        nationalite: '🇫🇷 France',
        taille: '1m78',
        poids: '73kg',
        piedFort: 'Droit',
        matchs: 24,
        buts: 10,
        passes: 11,
        cleanSheets: 0,
        cartonsJaunes: 3,
        cartonsRouges: 0,
        bio: 'Ailier vif et intelligent. Sébastien combine vitesse et technique pour déstabiliser les défenses.',
        parcours: ['US Lucé (2015-2019)', 'FC-Fulbert Chartres (2019-présent)']
    },
    {
        id: 'hugo-lambert-19',
        numero: 19,
        nom: 'Hugo Lambert',
        prenom: 'Hugo',
        nomComplet: 'Hugo Lambert',
        poste: 'Attaquant',
        position: 'attaquant',
        avatar: '⚡',
        age: 24,
        dateNaissance: '16/11/2000',
        nationalite: '🇫🇷 France',
        taille: '1m81',
        poids: '76kg',
        piedFort: 'Droit',
        matchs: 16,
        buts: 5,
        passes: 3,
        cleanSheets: 0,
        cartonsJaunes: 1,
        cartonsRouges: 0,
        bio: 'Jeune attaquant prometteur issu de la formation. Hugo montre de belles qualités et progresse.',
        parcours: ['FC-Fulbert U19 (2018-2020)', 'FC-Fulbert Senior (2020-présent)']
    },
    {
        id: 'dylan-fontaine-20',
        numero: 20,
        nom: 'Dylan Fontaine',
        prenom: 'Dylan',
        nomComplet: 'Dylan Fontaine',
        poste: 'Attaquant',
        position: 'attaquant',
        avatar: '⚡',
        age: 22,
        dateNaissance: '30/05/2002',
        nationalite: '🇫🇷 France',
        taille: '1m77',
        poids: '72kg',
        piedFort: 'Gauche',
        matchs: 12,
        buts: 3,
        passes: 2,
        cleanSheets: 0,
        cartonsJaunes: 0,
        cartonsRouges: 0,
        bio: 'Espoir offensif du club. Dylan apporte de la fraîcheur et de l\'envie en sortie de banc.',
        parcours: ['FC-Fulbert U19 (2019-2022)', 'FC-Fulbert Senior (2022-présent)']
    },
    {
        id: 'nathan-gauthier-21',
        numero: 21,
        nom: 'Nathan Gauthier',
        prenom: 'Nathan',
        nomComplet: 'Nathan Gauthier',
        poste: 'Attaquant',
        position: 'attaquant',
        avatar: '⚡',
        age: 23,
        dateNaissance: '08/08/2001',
        nationalite: '🇫🇷 France',
        taille: '1m79',
        poids: '74kg',
        piedFort: 'Droit',
        matchs: 10,
        buts: 2,
        passes: 1,
        cleanSheets: 0,
        cartonsJaunes: 1,
        cartonsRouges: 0,
        bio: 'Jeune attaquant polyvalent capable d\'évoluer sur différents postes offensifs.',
        parcours: ['FC-Fulbert U19 (2019-2021)', 'FC-Fulbert Senior (2021-présent)']
    }
];