// ===== DONNÉES JOUEURS FC-FULBERT - VERSION ANIME =====

const playersData = [
    // GARDIENS
    {
        id: 'naruto-uzumaki-1',
        numero: 1,
        nom: 'Naruto Uzumaki',
        prenom: 'Naruto',
        nomComplet: 'Naruto Uzumaki',
        poste: 'Gardien de but',
        position: 'gardien',
        avatar: '🧤',
        age: 30,
        dateNaissance: '10/10/1994',
        nationalite: '🇯🇵 Japon',
        taille: '1m88',
        poids: '85kg',
        piedFort: 'Droit',
        matchs: 26,
        buts: 0,
        passes: 0,
        cleanSheets: 12,
        cartonsJaunes: 2,
        cartonsRouges: 0,
        bio: 'Gardien légendaire du village de Konoha. Naruto protège les cages du FC-Fulbert avec la même détermination qu\'il mettait à devenir Hokage. Ses réflexes surhumains et son chakra illimité font de lui un rempart infranchissable.',
        parcours: ['Académie Ninja Konoha (2012-2016)', 'FC-Fulbert Chartres (2016-présent)']
    },
    {
        id: 'kakashi-hatake-16',
        numero: 16,
        nom: 'Kakashi Hatake',
        prenom: 'Kakashi',
        nomComplet: 'Kakashi Hatake',
        poste: 'Gardien de but',
        position: 'gardien',
        avatar: '🧤',
        age: 24,
        dateNaissance: '15/09/2000',
        nationalite: '🇯🇵 Japon',
        taille: '1m85',
        poids: '80kg',
        piedFort: 'Gauche',
        matchs: 0,
        buts: 0,
        passes: 0,
        cleanSheets: 0,
        cartonsJaunes: 0,
        cartonsRouges: 0,
        bio: 'Le ninja copieur attend son heure sur le banc. Son Sharingan lui permettra de copier les techniques adverses quand il entrera en jeu.',
        parcours: ['FC-Fulbert U19 (2018-2020)', 'FC-Fulbert Senior (2020-présent)']
    },
    
    // DÉFENSEURS
    {
        id: 'levi-ackerman-2',
        numero: 2,
        nom: 'Levi Ackerman',
        prenom: 'Levi',
        nomComplet: 'Levi Ackerman',
        poste: 'Arrière droit',
        position: 'defenseur',
        avatar: '🛡️',
        age: 28,
        dateNaissance: '25/12/1996',
        nationalite: '🇩🇪 Allemagne',
        taille: '1m82',
        poids: '78kg',
        piedFort: 'Droit',
        matchs: 24,
        buts: 2,
        passes: 5,
        cleanSheets: 0,
        cartonsJaunes: 4,
        cartonsRouges: 0,
        bio: 'Le soldat le plus fort de l\'humanité apporte sa rigueur et sa précision chirurgicale sur le côté droit. Ses montées dévastatrices rappellent ses attaques contre les Titans.',
        parcours: ['Bataillon d\'exploration (2014-2019)', 'FC-Fulbert Chartres (2019-présent)']
    },
    {
        id: 'eren-yeager-3',
        numero: 3,
        nom: 'Eren Yeager',
        prenom: 'Eren',
        nomComplet: 'Eren Yeager',
        poste: 'Arrière gauche',
        position: 'defenseur',
        avatar: '🛡️',
        age: 26,
        dateNaissance: '30/03/1998',
        nationalite: '🇩🇪 Allemagne',
        taille: '1m80',
        poids: '76kg',
        piedFort: 'Gauche',
        matchs: 23,
        buts: 1,
        passes: 7,
        cleanSheets: 0,
        cartonsJaunes: 3,
        cartonsRouges: 0,
        bio: 'Déterminé et agressif, Eren défend son camp avec une rage qui rappelle sa transformation en Titan. Son désir de liberté se traduit par des montées offensives spectaculaires.',
        parcours: ['Mur Maria FC (2016-2020)', 'FC-Fulbert Chartres (2020-présent)']
    },
    {
        id: 'saitama-4',
        numero: 4,
        nom: 'Saitama',
        prenom: 'Saitama',
        nomComplet: 'Saitama',
        poste: 'Défenseur central',
        position: 'defenseur',
        avatar: '🛡️',
        age: 29,
        dateNaissance: '01/01/1996',
        nationalite: '🇯🇵 Japon',
        taille: '1m85',
        poids: '82kg',
        piedFort: 'Droit',
        matchs: 25,
        buts: 3,
        passes: 2,
        cleanSheets: 0,
        cartonsJaunes: 6,
        cartonsRouges: 1,
        bio: 'One Punch Man dans la défense. Saitama arrête tous les attaquants avec une facilité déconcertante. Son entrainement de 100 pompes par jour en fait un roc inébranlable.',
        parcours: ['Hero Association (2014-2017)', 'FC-Fulbert Chartres (2017-présent)']
    },
    {
        id: 'goku-5',
        numero: 5,
        nom: 'Son Goku',
        prenom: 'Goku',
        nomComplet: 'Son Goku',
        poste: 'Défenseur central',
        position: 'defenseur',
        avatar: '🛡️',
        age: 27,
        dateNaissance: '16/04/1997',
        nationalite: '🇯🇵 Japon',
        taille: '1m83',
        poids: '79kg',
        piedFort: 'Gauche',
        matchs: 22,
        buts: 1,
        passes: 3,
        cleanSheets: 0,
        cartonsJaunes: 5,
        cartonsRouges: 0,
        bio: 'Le Saiyan de la défense. Goku compense par son ultra-instinct défensif qui lui permet d\'anticiper toutes les attaques adverses avant même qu\'elles ne se produisent.',
        parcours: ['Capsule Corp FC (2015-2019)', 'FC-Fulbert Chartres (2019-présent)']
    },
    {
        id: 'zoro-12',
        numero: 12,
        nom: 'Roronoa Zoro',
        prenom: 'Zoro',
        nomComplet: 'Roronoa Zoro',
        poste: 'Défenseur',
        position: 'defenseur',
        avatar: '🛡️',
        age: 25,
        dateNaissance: '11/11/1999',
        nationalite: '🇯🇵 Japon',
        taille: '1m81',
        poids: '77kg',
        piedFort: 'Droit',
        matchs: 15,
        buts: 0,
        passes: 2,
        cleanSheets: 0,
        cartonsJaunes: 2,
        cartonsRouges: 0,
        bio: 'Le bretteur égaré de la défense. Zoro se perd souvent sur le terrain mais sa détermination d\'acier fait de lui un défenseur redoutable. Ses trois styles de jeu perturbent les attaquants.',
        parcours: ['Équipage du Chapeau de Paille U19 (2017-2019)', 'FC-Fulbert Senior (2019-présent)']
    },
    {
        id: 'vegeta-15',
        numero: 15,
        nom: 'Vegeta',
        prenom: 'Vegeta',
        nomComplet: 'Vegeta',
        poste: 'Défenseur',
        position: 'defenseur',
        avatar: '🛡️',
        age: 23,
        dateNaissance: '01/01/2001',
        nationalite: '🇯🇵 Japon',
        taille: '1m79',
        poids: '74kg',
        piedFort: 'Gauche',
        matchs: 10,
        buts: 0,
        passes: 1,
        cleanSheets: 0,
        cartonsJaunes: 1,
        cartonsRouges: 0,
        bio: 'Le Prince des Saiyans en défense. Vegeta refuse de perdre et sa fierté le pousse à repousser toutes les attaques. Son Final Flash défensif est légendaire.',
        parcours: ['FC-Fulbert U19 (2019-2021)', 'FC-Fulbert Senior (2021-présent)']
    },

    // MILIEUX
    {
        id: 'light-yagami-6',
        numero: 6,
        nom: 'Light Yagami',
        prenom: 'Light',
        nomComplet: 'Light Yagami',
        poste: 'Milieu défensif',
        position: 'milieu',
        avatar: '⚙️',
        age: 27,
        dateNaissance: '28/02/1997',
        nationalite: '🇯🇵 Japon',
        taille: '1m76',
        poids: '72kg',
        piedFort: 'Droit',
        matchs: 25,
        buts: 3,
        passes: 6,
        cleanSheets: 0,
        cartonsJaunes: 7,
        cartonsRouges: 0,
        bio: 'Le stratège du milieu de terrain. Light calcule chaque passe avec une précision mathématique. Son Death Note tactique terrorise les adversaires.',
        parcours: ['Tokyo Academy (2015-2018)', 'FC-Fulbert Chartres (2018-présent)']
    },
    {
        id: 'edward-elric-8',
        numero: 8,
        nom: 'Edward Elric',
        prenom: 'Edward',
        nomComplet: 'Edward Elric',
        poste: 'Milieu relayeur',
        position: 'milieu',
        avatar: '⚙️',
        age: 26,
        dateNaissance: '03/02/1998',
        nationalite: '🇩🇪 Allemagne',
        taille: '1m78',
        poids: '73kg',
        piedFort: 'Droit',
        matchs: 24,
        buts: 5,
        passes: 8,
        cleanSheets: 0,
        cartonsJaunes: 3,
        cartonsRouges: 0,
        bio: 'L\'alchimiste du milieu de terrain. Edward transforme chaque action en or grâce à son intelligence tactique. Sa loi de l\'échange équivalent : un effort pour un but.',
        parcours: ['Amestris FC (2016-2019)', 'FC-Fulbert Chartres (2019-présent)']
    },
    {
        id: 'luffy-10',
        numero: 10,
        nom: 'Monkey D. Luffy',
        prenom: 'Luffy',
        nomComplet: 'Monkey D. Luffy',
        poste: 'Meneur de jeu',
        position: 'milieu',
        avatar: '⚙️',
        age: 29,
        dateNaissance: '05/05/1995',
        nationalite: '🇯🇵 Japon',
        taille: '1m75',
        poids: '71kg',
        piedFort: 'Gauche',
        matchs: 26,
        buts: 8,
        passes: 14,
        cleanSheets: 0,
        cartonsJaunes: 2,
        cartonsRouges: 0,
        bio: 'Le futur Roi des Pirates est le capitaine créatif du FC-Fulbert. Luffy étire le jeu avec ses passes Gum-Gum qui déstabilisent toutes les défenses. Son rêve : la Coupe du Monde !',
        parcours: ['East Blue FC (2013-2017)', 'FC-Fulbert Chartres (2017-présent)']
    },
    {
        id: 'kaneki-14',
        numero: 14,
        nom: 'Ken Kaneki',
        prenom: 'Ken',
        nomComplet: 'Ken Kaneki',
        poste: 'Milieu offensif',
        position: 'milieu',
        avatar: '⚙️',
        age: 24,
        dateNaissance: '20/12/2000',
        nationalite: '🇯🇵 Japon',
        taille: '1m77',
        poids: '70kg',
        piedFort: 'Gauche',
        matchs: 20,
        buts: 4,
        passes: 7,
        cleanSheets: 0,
        cartonsJaunes: 2,
        cartonsRouges: 0,
        bio: 'Mi-humain, mi-goule, totalement talentueux. Kaneki apporte une dualité unique au jeu, capable de défendre et attaquer avec la même intensité dévorante.',
        parcours: ['Anteiku FC U19 (2018-2020)', 'FC-Fulbert Senior (2020-présent)']
    },
    {
        id: 'lelouch-17',
        numero: 17,
        nom: 'Lelouch vi Britannia',
        prenom: 'Lelouch',
        nomComplet: 'Lelouch vi Britannia',
        poste: 'Milieu',
        position: 'milieu',
        avatar: '⚙️',
        age: 25,
        dateNaissance: '05/12/1999',
        nationalite: '🇬🇧 Angleterre',
        taille: '1m74',
        poids: '69kg',
        piedFort: 'Droit',
        matchs: 18,
        buts: 2,
        passes: 5,
        cleanSheets: 0,
        cartonsJaunes: 3,
        cartonsRouges: 0,
        bio: 'Le génie stratégique aux commandes. Avec son Geass, Lelouch force les adversaires à faire exactement ce qu\'il veut. Chaque match est une partie d\'échecs qu\'il gagne.',
        parcours: ['Ashford Academy (2017-2020)', 'FC-Fulbert Chartres (2020-présent)']
    },
    {
        id: 'tanjiro-18',
        numero: 18,
        nom: 'Tanjiro Kamado',
        prenom: 'Tanjiro',
        nomComplet: 'Tanjiro Kamado',
        poste: 'Milieu',
        position: 'milieu',
        avatar: '⚙️',
        age: 23,
        dateNaissance: '14/07/2001',
        nationalite: '🇯🇵 Japon',
        taille: '1m79',
        poids: '74kg',
        piedFort: 'Droit',
        matchs: 12,
        buts: 1,
        passes: 3,
        cleanSheets: 0,
        cartonsJaunes: 1,
        cartonsRouges: 0,
        bio: 'Le pourfendeur de démons au milieu de terrain. Tanjiro utilise la respiration de l\'eau pour contrôler le tempo du match. Son odorat surdéveloppé détecte les intentions adverses.',
        parcours: ['Demon Slayer Corps U19 (2019-2021)', 'FC-Fulbert Senior (2021-présent)']
    },

    // ATTAQUANTS
    {
        id: 'ichigo-7',
        numero: 7,
        nom: 'Ichigo Kurosaki',
        prenom: 'Ichigo',
        nomComplet: 'Ichigo Kurosaki',
        poste: 'Ailier droit',
        position: 'attaquant',
        avatar: '⚡',
        age: 28,
        dateNaissance: '15/07/1996',
        nationalite: '🇯🇵 Japon',
        taille: '1m80',
        poids: '75kg',
        piedFort: 'Gauche',
        matchs: 25,
        buts: 12,
        passes: 9,
        cleanSheets: 0,
        cartonsJaunes: 2,
        cartonsRouges: 0,
        bio: 'Le Shinigami remplaçant sur l\'aile droite. Ichigo coupe les défenses avec son Zanpakuto offensif. Son Bankai lui permet d\'atteindre des vitesses incroyables.',
        parcours: ['Soul Society FC (2014-2018)', 'FC-Fulbert Chartres (2018-présent)']
    },
    {
        id: 'deku-9',
        numero: 9,
        nom: 'Izuku Midoriya',
        prenom: 'Izuku',
        nomComplet: 'Izuku Midoriya',
        poste: 'Avant-centre',
        position: 'attaquant',
        avatar: '⚡',
        age: 26,
        dateNaissance: '15/07/1998',
        nationalite: '🇯🇵 Japon',
        taille: '1m82',
        poids: '77kg',
        piedFort: 'Droit',
        matchs: 26,
        buts: 18,
        passes: 4,
        cleanSheets: 0,
        cartonsJaunes: 1,
        cartonsRouges: 0,
        bio: 'Héritier du One For All, Deku est le buteur numéro 1 du FC-Fulbert. Avec ses tirs à 1.000.000%, il pulvérise les filets adverses. Plus Ultra dans chaque action !',
        parcours: ['UA High School (2016-2019)', 'FC-Fulbert Chartres (2019-présent)']
    },
    {
        id: 'killua-11',
        numero: 11,
        nom: 'Killua Zoldyck',
        prenom: 'Killua',
        nomComplet: 'Killua Zoldyck',
        poste: 'Ailier gauche',
        position: 'attaquant',
        avatar: '⚡',
        age: 27,
        dateNaissance: '07/07/1998',
        nationalite: '🇯🇵 Japon',
        taille: '1m78',
        poids: '73kg',
        piedFort: 'Droit',
        matchs: 24,
        buts: 10,
        passes: 11,
        cleanSheets: 0,
        cartonsJaunes: 3,
        cartonsRouges: 0,
        bio: 'L\'assassin reconverti en ailier foudroyant. Killua utilise son Godspeed pour traverser les défenses en un éclair. Sa vitesse électrique est impossible à stopper.',
        parcours: ['Zoldyck Family FC (2015-2019)', 'FC-Fulbert Chartres (2019-présent)']
    },
    {
        id: 'kirito-19',
        numero: 19,
        nom: 'Kirito',
        prenom: 'Kirito',
        nomComplet: 'Kazuto Kirigaya',
        poste: 'Attaquant',
        position: 'attaquant',
        avatar: '⚡',
        age: 24,
        dateNaissance: '07/10/2000',
        nationalite: '🇯🇵 Japon',
        taille: '1m81',
        poids: '76kg',
        piedFort: 'Droit',
        matchs: 16,
        buts: 5,
        passes: 3,
        cleanSheets: 0,
        cartonsJaunes: 1,
        cartonsRouges: 0,
        bio: 'Le héros de Sword Art Online apporte son style dual-wielding sur le terrain. Kirito utilise ses deux pieds avec la même efficacité mortelle que ses deux épées.',
        parcours: ['Aincrad FC U19 (2018-2020)', 'FC-Fulbert Senior (2020-présent)']
    },
    {
        id: 'natsu-20',
        numero: 20,
        nom: 'Natsu Dragneel',
        prenom: 'Natsu',
        nomComplet: 'Natsu Dragneel',
        poste: 'Attaquant',
        position: 'attaquant',
        avatar: '⚡',
        age: 22,
        dateNaissance: '01/01/2002',
        nationalite: '🇯🇵 Japon',
        taille: '1m77',
        poids: '72kg',
        piedFort: 'Gauche',
        matchs: 12,
        buts: 3,
        passes: 2,
        cleanSheets: 0,
        cartonsJaunes: 0,
        cartonsRouges: 0,
        bio: 'Le Dragon Slayer de feu sur le front de l\'attaque. Natsu met le feu aux défenses adverses avec ses tirs enflammés. All Fired Up pour chaque match !',
        parcours: ['Fairy Tail Guild U19 (2019-2022)', 'FC-Fulbert Senior (2022-présent)']
    },
    {
        id: 'todoroki-21',
        numero: 21,
        nom: 'Shoto Todoroki',
        prenom: 'Shoto',
        nomComplet: 'Shoto Todoroki',
        poste: 'Attaquant',
        position: 'attaquant',
        avatar: '⚡',
        age: 23,
        dateNaissance: '11/01/2001',
        nationalite: '🇯🇵 Japon',
        taille: '1m79',
        poids: '74kg',
        piedFort: 'Droit',
        matchs: 10,
        buts: 2,
        passes: 1,
        cleanSheets: 0,
        cartonsJaunes: 1,
        cartonsRouges: 0,
        bio: 'Maître du feu et de la glace, Todoroki apporte une polyvalence unique en attaque. Ses tirs glacés ou brûlants surprennent tous les gardiens.',
        parcours: ['UA High School U19 (2019-2021)', 'FC-Fulbert Senior (2021-présent)']
    }
];